### PR TITLE
audiounit,coreaudio: fix kAudioObjectPropertyElementMaster deprecation

### PR DESCRIPTION
**Pull request by sreimers**
```
modules/audiounit/recorder.c:202:3: warning: 'kAudioObjectPropertyElementMaster' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
                kAudioObjectPropertyElementMaster };
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                kAudioObjectPropertyElementMain
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreAudio.framework/Headers/AudioHa
rdwareBase.h:208:5: note: 'kAudioObjectPropertyElementMaster' has been explicitly marked deprecated here
    kAudioObjectPropertyElementMaster API_DEPRECATED_WITH_REPLACEMENT("kAudioObjectPropertyElementMain", macos(10.0, 12.0), ios(2.0, 15.0), watchos(1.0, 8.0
), tvos(9.0, 15.0)) = kAudioObjectPropertyElementMain
    ^                                
  OC [m]  build-x86_64/modules/avcapture/avcapture.o
1 warning generated. 
```

```
modules/coreaudio/coreaudio.c:30:3: warning: 'kAudioObjectPropertyElementMaster' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
                kAudioObjectPropertyElementMaster
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                kAudioObjectPropertyElementMain
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreAudio.framework/Headers/AudioHa
rdwareBase.h:208:5: note: 'kAudioObjectPropertyElementMaster' has been explicitly marked deprecated here
    kAudioObjectPropertyElementMaster API_DEPRECATED_WITH_REPLACEMENT("kAudioObjectPropertyElementMain", macos(10.0, 12.0), ios(2.0, 15.0), watchos(1.0, 8.0
), tvos(9.0, 15.0)) = kAudioObjectPropertyElementMain
    ^                                                                         
1 warning generated.                                                          
```

### CODE REVIEW

**Comment by alfredh** [comment]
this broke the build on my machine, I am on OSX 10.15:

```
  CC [M]  build-x86_64/modules/audiounit/audiounit.o
  CC [M]  build-x86_64/modules/audiounit/sess.o
  CC [M]  build-x86_64/modules/audiounit/player.o
  CC [M]  build-x86_64/modules/audiounit/recorder.o
modules/audiounit/recorder.c:202:3: error: use of undeclared identifier 'kAudioObjectPropertyElementMain'; did you mean
      'kAudioObjectPropertyElementName'?
                kAudioObjectPropertyElementMain };
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                kAudioObjectPropertyElementName
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreAudio.framework/Headers/AudioHardwareBase.h:331:5: note: 
      'kAudioObjectPropertyElementName' declared here
    kAudioObjectPropertyElementName         = 'lchn',
    ^
1 error generated.
make: *** [build-x86_64/modules/audiounit/recorder.o] Error 1
```

**Comment by sreimers** [comment]
Thats strange it should be available since 10.12: https://developer.apple.com/documentation/coreaudio/1494464-anonymous/kaudioobjectpropertyelementmain?language=objc

Is MACOSX_DEPLOYMENT_TARGET set?

**Comment by alfredh** [comment]
```
Alfreds-MacBook-Pro:baresip alfredh$ make info
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
info - baresip version 2.4.0
  MODULES:       account auconv auresamp contact ctrl_tcp debug_cmd ebuacip echo fakevideo httpd ice menu mwi natpmp presence rtcpsummary selfview serreg srtp stun turn uuid vidbridge vidinfo vumeter mixausrc mixminus multicast aubridge aufile ausine aac av1 audiounit avcapture avcodec avformat codec2 cons coreaudio dtls_srtp g711 g722 g7221 g726 gsm ctrl_dbus gst gst_video gtk httpreq jack l16 opus_multistream mpa mqtt netroam opus plc portaudio pulse sdl snapshot sndfile stdio syslog vp8 vp9 x11 
  MACHINE:       x86_64-apple-darwin19.6.0
  ARCH:          x86_64
  OS:            darwin
  BUILD:         build-x86_64
  PKG_CONFIG:    0.29.2
  CCACHE:        
  CC:            gcc 12.0.0 (12.x)
  CFLAGS:        -I/opt/local/include -Wall -Wextra -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wbad-function-cast -Wsign-compare -Wnested-externs -Wshadow -Waggregate-return -Wcast-align -Wold-style-definition -Wvla  -Wshorten-64-to-32 -g -fPIC -dynamic -DDARWIN -Wshorten-64-to-32 -DOS="darwin" -std=c11 -DHAVE_ATOMIC -pedantic -DARCH="x86_64" -DUSE_OPENSSL -DUSE_TLS -DUSE_OPENSSL_DTLS -DUSE_DTLS -DUSE_OPENSSL_SRTP -DUSE_DTLS_SRTP -DUSE_ZLIB -DHAVE_PTHREAD -DHAVE_GETIFADDRS -DHAVE_STRERROR_R -DHAVE_GETOPT -DHAVE_NET_ROUTE_H -DHAVE_SYS_SYSCTL_H -DHAVE_STDBOOL_H -DHAVE_INET6 -DHAVE_SYSLOG -DHAVE_RESOLV -DHAVE_EXECINFO -DHAVE_FORK -DHAVE_PWD_H -DHAVE_SELECT -DHAVE_SELECT_H -DHAVE_SETRLIMIT -DHAVE_SIGNAL -DHAVE_SYS_TIME_H -DHAVE_KQUEUE -DHAVE_UNAME -DHAVE_UNISTD_H -DHAVE_STRINGS_H -DVERSION="2.4.0" -DVER_MAJOR= -DVER_MINOR= -DVER_PATCH=  -I. -Iinclude -I../re/include -I../rem/include -DPREFIX="/usr/local" -DMOD_PATH="/usr/local/lib/baresip/modules" -DSHARE_PATH="/usr/local/share/baresip"
  DFLAGS:        -MD
  LFLAGS:        -L/opt/local/lib -fPIC -framework SystemConfiguration -framework CoreFoundation 
  SH_LFLAGS:     -dynamiclib
  MOD_LFLAGS:    -undefined dynamic_lookup
  APP_LFLAGS:    
  LIBS:          -lresolv -lssl -lcrypto -lz -lpthread -L../rem -lrem -lm
  LIBRE_MK:      ../re/mk/re.mk
  LIBRE_PATH:    ../re
  LIBRE_INC:     ../re/include
  LIBRE_SO:      ../re
  OPENSSL_OPT:   
  USE_OPENSSL:   yes
  USE_OPENSSL_AES:   yes
  USE_OPENSSL_HMAC:  yes
  USE_TLS:       yes
  USE_DTLS:      yes
  USE_DTLS_SRTP: yes
  USE_ZLIB:      yes
  GCOV:          
  GPROF:         
  CROSS_COMPILE: 
  SYSROOT:       /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr
  SYSROOT_ALT:   /opt/local
  LIB_SUFFIX:    .dylib
  MOD_SUFFIX:    .so
  BIN_SUFFIX:    
Alfreds-MacBook-Pro:baresip alfredh$ make coreaudio.so
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
  CC [M]  build-x86_64/modules/coreaudio/coreaudio.o
modules/coreaudio/coreaudio.c:30:3: error: use of undeclared identifier 'kAudioObjectPropertyElementMain'; did you mean
      'kAudioObjectPropertyElementName'?
                kAudioObjectPropertyElementMain
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                kAudioObjectPropertyElementName
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreAudio.framework/Headers/AudioHardwareBase.h:331:5: note: 
      'kAudioObjectPropertyElementName' declared here
    kAudioObjectPropertyElementName         = 'lchn',
    ^
1 error generated.
make: *** [build-x86_64/modules/coreaudio/coreaudio.o] Error 1
```

**Comment by sreimers** [comment]
Can you try this PR: https://github.com/baresip/baresip/pull/1885
